### PR TITLE
Fix intermittent DateWidget test

### LINKED ISSUE #162: Intermittent failure on DateWidget tests

### PR DESCRIPTION
**Pull request by magopian**
Fixes #162

### CODE REVIEW

File: test/StringField_test.js [hunk 1]
```diff
@@ -466,8 +466,10 @@ describe("StringField", () => {
 
         return SimulateAsync().click(node.querySelector("a.btn-now"))
           .then(() => {
-            const expected = toDateString(parseDateString(new Date().toJSON(), true));
-            expect(comp.state.formData).eql(expected);
+            // Test that the two DATETIMEs to be within 5seconds of each other.
```
Comment (almet) [inline test/StringField_test.js]: nit: missing a space between 5 and seconds.

Comment (magopian) [inline test/StringField_test.js]: Good catch, thanks!

**Comment by n1k0** [comment]
LGTM, r+.
