### PR TITLE
Fixes #150: Native date time widgets.

### LINKED ISSUE #150: "ui:widget": "date" to native input type=date ?
### Description

The date widget imo seems like a steps backwards in usability.

Not sure how to use the native https://html.spec.whatwg.org/multipage/forms.html#date-state-(type=date) instead.

### Steps to Reproduce

1. http://s3.jptdev.com/2016-04-20/date.html
2. Marvel at dropdown selectors to choose a date
3. Wonder if it's possible to use type=date instead

#### Expected behavior

Use the native browser date picker.
http://caniuse.com/#feat=input-datetime

#### Actual behavior

Drop down select boxes

### Version

https://npmcdn.com/react-jsonschema-form@0.25.0/dist/react-jsonschema-form.js

### PR DESCRIPTION
**Pull request by n1k0**
WiP, refs #150 /cc @kaihendry 

This adds new native date and datetime widgets which are now used by default, and demotes previous default select-based date widgets as alternative ones.

#### Todo

- [x] Update docs
- [x] Write tests ~~(hard as jsdom doesn't have a clue what these inputs are)~~

### CODE REVIEW

**Comment by n1k0** [comment]
We should probably keep the select-based date widgets as default ones, as support isn't great across platforms just yet.

File: playground/samples/date.js [hunk 1]
```diff
@@ -0,0 +1,54 @@
+module.exports = {
+  schema: {
+    title: "Date and time widgets",
+    type: "object",
+    properties: {
+      native: {
+        title: "Native",
+        description: "Note that a few browsers support these.",
```
Comment (leplatrem) [inline playground/samples/date.js]: nit: `May not work on some browsers` could be enough ?

File: test/StringField_test.js [hunk 2]
```diff
@@ -175,12 +175,14 @@ describe("StringField", () => {
     });
   });
 
-  describe("DateTimeWidget", () => {
+  describe("AltDateTimeWidget", () => {
```
Comment (leplatrem) [inline test/StringField_test.js]: You haven't any tests for the native ones right ?

Comment (n1k0) [inline test/StringField_test.js]: Nope, see notes & todo in the bug description.

**Comment by leplatrem** [comment]
FYI it works like a charm on Firefox mobile:

photo_2016-04-22_19-26-18
photo_2016-04-22_19-26-27

**Comment by almet** [comment]
> after discussing about that with @leplatrem, we decided to keep it this way.

Can we know what the turning point was?

As the default HTML5 date input doesn't work on almost all non-mobile platforms. I would suggest having something that works for all platforms by default instead.

**Comment by n1k0** [comment]
> Can we know what the turning point was?

Pushing and promoting Web standards.

**Comment by n1k0** [comment]
Note: For Firefox, [bug 825294](https://bugzilla.mozilla.org/show_bug.cgi?id=825294) should land anytime soon. MSDN strangely declare it [supported](https://msdn.microsoft.com/en-us/library/mt584200%28v=vs.85%29.aspx), so maybe it's just matter of time for it to land on a stable version?

**Comment by almet** [comment]
Mouarf, pushing and promoting web standards is great, but we should make our library users aware that this will not work for most of their users, and probably propose an alternative solution.

**Comment by n1k0** [comment]
> we should make our library users aware that this will not work for most of their users, and probably propose an alternative solution

That's probably why I've added a specific section in the documentation along providing alternative widgets compatible with those other platforms.

**Comment by almet** [comment]
Perfect! :)

File: README.md [hunk 3]
```diff
@@ -215,13 +216,22 @@ Here's a list of supported alternative widgets for different JSONSchema data typ
...
+The built-in string field also supports the JSONSchema `format` property, and will render an appropriate widget by default for the following string formats:
 
-- `date-time`: Six `select` elements are used to select the year, the month, the day, the hour, the minute and the second;
-    * If you don't want to deal with time, a `"ui:widget": "date"` uiSchema widget is alternatively available, exposing three selects for year, month and day only;
 - `email`: An `input[type=email]` element is used;
 - `uri`: An `input[type=url]` element is used;
-- More formats could be supported in a near future, feel free to help us going faster!
+- `date-time`: By default, an `input[type=datetime-local]` element is used; if you solely want to rely on a date, a `date` uiSchema alternative widget is available:
+
+![](http://i.imgur.com/xqu6Lcp.png)
```
Comment (almet) [inline README.md]: I believe imgur isn't a good place to host these images, as the pictures could disapear any time. Should we host them in this very repository instead?

Comment (n1k0) [inline README.md]: There's no easy way to make github serving images hosted in the repo itself. Also, if these are ever gone it's no big deal to redo some captures.

**Comment by n1k0** [comment]
I'm gonna land this with r=me.

File: README.md (hunk 3 above)
Comment (almet) [inline README.md]: I believe it's possible to do it like that:

```
![alt tag](https://raw.githubusercontent.com/mozilla-services/react-jsonschema-form/master/path/to/img.png)
```
