### PR TITLE
Fix multiple bugs related to switching between anyOf/oneOf options

### LINKED ISSUE #1168: Broken behaviour for oneOf inside array
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Using `oneOf` inside an array, where one branch is an integer and the other branch is an object is broken. When selecting the second option, the correct fields are not rendered at all.

```
{
  "type": "object",
  "properties": {
    "myArray": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "integer"
          },
          {
            "type": "object",
            "properties": {
              "elt1": {
                "type": "integer"
              },
              "elt2": {
                "type": "string"
              }
            },
            "required": [
              "elt1",
              "elt2"
            ]
          }
        ]
      }
    }
  }
}
```

[playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJteUFycmF5Ijp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7Im9uZU9mIjpbeyJ0eXBlIjoiaW50ZWdlciJ9LHsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZWx0MSI6eyJ0eXBlIjoiaW50ZWdlciJ9LCJlbHQyIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbImVsdDEiLCJlbHQyIl19XX19fX0sInVpU2NoZW1hIjp7fX0=)

Originally reported by @Rasstrelnikov here https://github.com/mozilla-services/react-jsonschema-form/issues/1141#issuecomment-460835801

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #1168

- Fixed a bug that would prevent input fields from rendering when
switching between a non-object type option and an object type option
- Fixed a bug where options would incorrectly change when entering
values if a subschema with multiple required fields is used
- Fixed a bug where switching from an object type option to a non-object
type option would result in an input field containing the value [Object object]

Change-type: patch
Signed-off-by: Lucian <lucian.buzzo@gmail.com>

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: src/components/fields/MultiSchemaField.js [hunk 1]
```diff
@@ -85,7 +89,14 @@ class AnyOfField extends Component {
...
 
-    if (guessType(formData) === "object") {
+    const newOption = options[selectedOption];
+
+    // If the new option is of type object and the current data is an object,
+    // discard properties added using the old option.
+    if (
+      guessType(formData) === "object" &&
+      (newOption.type === "object" || newOption.properties)
+    ) {
```
Comment (epicfaace) [inline src/components/fields/MultiSchemaField.js]: I'm having trouble understanding how this piece of code fixes the issue "should empty the form data when switching from an option of type 'object'." It looks like in that case, `newOption` would not be an object, so then the properties added by the old option would not be deleted?

File: src/components/fields/ObjectField.js [hunk 2]
```diff
@@ -237,7 +237,7 @@ class ObjectField extends Component {
               errorSchema={errorSchema[name]}
               idSchema={idSchema[name]}
               idPrefix={idPrefix}
-              formData={formData[name]}
+              formData={(formData || {})[name]}
```
[the remark this answers is not in the document]
Comment (LucianBuzzo) [reply src/components/fields/ObjectField.js]: `formData` can be null if you have just added an item to an array

File: src/utils.js [hunk 3]
```diff
@@ -727,7 +727,7 @@ export function toIdSchema(
       field,
       fieldId,
       definitions,
-      formData[name],
+      formData,
```
[the remark this answers is not in the document]
Comment (LucianBuzzo) [reply src/utils.js]: This fixes and issue where an idSchema is being created, but `formData` is null. It turns out that the code path that this effects (nested object schemas) isn't tested, so I'm going to improve test coverage here and rework this change.

File: test/anyOf_test.js [hunk 4]
```diff
@@ -530,24 +530,23 @@ describe("anyOf", () => {
   });
 
   describe("Arrays", () => {
-    it("should correctly render form inputs for anyOf inside array items", () => {
```
[the remark this answers is not in the document]
Comment (LucianBuzzo) [reply test/anyOf_test.js]: I think this was a mistake

File: src/components/fields/MultiSchemaField.js (hunk 1 above)
Comment (LucianBuzzo) [reply src/components/fields/MultiSchemaField.js]: `newOption` is the schema that the form has changed to. When we move into this code path, `formData` will always get set to an object, which is undesirable if the new object is, for example, a string. Previously, if the value of `newOption` was `{ "type": "string" }`, and the `formData` gets set to an object, then the UI would display an input with the text `[Object object]`.

**Comment by LucianBuzzo** [comment]
@epicfaace Can you please re-review this PR when you have a chance?

**Comment by loctn** [comment]
Do not mean to rush you @epicfaace , but excited for this fix to land ^_^.

File: src/components/fields/MultiSchemaField.js (hunk 1 above)
Comment (epicfaace) [reply src/components/fields/MultiSchemaField.js]: Makes sense -- thanks!

File: src/utils.js [hunk 5]
```diff
@@ -732,7 +732,9 @@ export function toIdSchema(
       field,
       fieldId,
       definitions,
-      formData[name],
+      // Its possible that formData is not an object, this can happen if an
```
Comment (epicfaace) [inline src/utils.js]:
```suggestion
      // It's possible that formData is not an object, this can happen if an
```

File: src/utils.js [hunk 6]
```diff
@@ -732,7 +732,9 @@ export function toIdSchema(
       field,
       fieldId,
       definitions,
-      formData[name],
+      // It's possible that formData is not an object, this can happen if an
```
Comment (epicfaace) [inline src/utils.js]:
```suggestion
      // It's possible that formData is not an object -- this can happen if an
```

File: src/utils.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (epicfaace) [reply src/utils.js]: Makes sense -- thanks for the fix! Not sure how your initial change to `formData` fixes it, but it makes sense now with your change to `(formData || {})[name]`.
