### PR TITLE
Default type to `object` if undefined

### LINKED ISSUE #1265: Default type to `object` if undefined
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Can we default the `type` to `object` if it's undefined? We accept user submitted JSON Schemas and this is a common thing that people miss. I'm not 100% sure if it's valid JSON Schema or not, but https://www.jsonschemavalidator.net/ appears to say the following is valid:

```json
{
  "properties": {
    "a": {
      "type": "string"
    }
  }
}
```

But when passing that into this module, we get the following error:

image

Playground link: https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImEiOnsidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7fX0=

### Steps to Reproduce
1. Pass in a JSON Schema without a `type`
2. Observe that the [UnsupportedField](https://github.com/mozilla-services/react-jsonschema-form/blob/2d63594e075bba3b134ef09709c773a9ea037923/src/components/fields/UnsupportedField.js) is instantiated

#### Expected behavior
Default `type` to `object` if it is undefined
If `type` is set to something that is unknown, still create the `UnsupportedField` e.g. `type: 'someothertype'`

Affected blocks of code:
Could check for undefined in here and return `object`: https://github.com/mozilla-services/react-jsonschema-form/blob/2d63594e075bba3b134ef09709c773a9ea037923/src/utils.js#L68-L84

This is where it will bubble up to, but I don't think this code would have to change at all: https://github.com/mozilla-services/react-jsonschema-form/blob/2d63594e075bba3b134ef09709c773a9ea037923/src/components/fields/SchemaField.js#L49-L59

Happy to send over a PR for this if it'll get accepted! 

### Version
v1.5.0

### PR DESCRIPTION
**Pull request by domharrington**
### Reasons for making this change
Fixes #1265

Added tests and confirmed working on the local test app:
http://localhost:8080/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7ImEiOnsidHlwZSI6InN0cmluZyJ9fX0sInVpU2NoZW1hIjp7fX0=

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -76,6 +76,10 @@ export function getSchemaType(schema) {
     return "string";
   }
 
+  if ((!type && schema.properties) || schema.additionalProperties) {
```
Comment (epicfaace) [inline src/utils.js]: Is this necessary? Could we just make it

```suggestion
  if (schema.properties || schema.additionalProperties) {
```
Or does it need to be
```suggestion
  if (!type && (schema.properties || schema.additionalProperties)) {
```

Comment (domharrington) [reply src/utils.js]: Agree the latter is better. Making that change!

**Comment by epicfaace** [comment]
Thanks!
