### PR TITLE
Fixes #824

### LINKED ISSUE #824: Name should not be required for properties in data-url format
### Prerequisites

- [ Yes] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [Yes ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

[Thank you for this awesome library. I have been using it extensively. Our primary work for this library to build ui dynamically through custom widgets using materil-ui and some others. Recently I created a custom file upload widget using https://github.com/react-dropzone/react-dropzone  As I was going through documentation it says file widget only supports data-url. So i got bit worried how i will get to know file name since data-url does not contain file name. So I decided to skip name entirely continued my work. After completing file upload widget when I tested it, it kept on giving me this error file is not of type data-uri. Here is how I was setting its value
handleOnDropAccepeted(file){
        let uploadedFilesNames = [];

        let reader = new FileReader();
        reader.readAsDataURL(file[0]);
        reader.onloadend = () => {
            this.props.onChange(reader.result);
        }
    }

It boggled me for hours as I could not figure out why it is not working. Then upon looking into your code I saw you are also encoding file name there in base64 and if we did not encode file name in string it will complain saying string data is not valid data-uri. So please mention this in your documentation for custom file upload widget you also need to encode file name there as well. Here is how my code looks now
export const addNameToDataURI=(dataURL, name)=>{
  return dataURL.replace(";base64", `;name=${name};base64`);
}

handleOnDropAccepeted(file){
        let uploadedFilesNames = [];

        let reader = new FileReader();
        reader.readAsDataURL(file[0]);
        reader.onloadend = () => {
            this.props.onChange(addNameToDataURI(reader.result, file[0].name));
        }
    }

as you can see encoding name into file is basically function from your code source
]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

### PR DESCRIPTION
**Pull request by jorgerobles**
### Reasons for making this change

See Issue #824, made name not required.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated docs if needed
  - [X] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by jorgerobles** [comment]
Just a regex tweak.

**Comment by epicfaace** [comment]
Thanks @jorgerobles, good work 😀-- can you add a test as you did in https://github.com/mozilla-services/react-jsonschema-form/pull/967/files?

**Comment by edi9999** [comment]
It would be better indeed to have a regression test.

File: test/validate_test.js [hunk 1]
```diff
@@ -79,6 +79,32 @@ describe("Validation", () => {
...
+      beforeEach(() => {
+        const formData = {
+          dataUrlWithName: "data:text/plain;name=file1.txt;base64,x=",
+          dataUrlWithoutName: "data:text/plain;base64,x=",
+        };
+        const result = validateFormData(formData, schema);
+        errors = result.errors;
+      });
+
+      it("Both should be fine", () => {
```
Comment (epicfaace) [inline test/validate_test.js]: Thanks for the test -- don't mean to be nitpicky, but it would really be great and cleaner if you could have separate `it` functions for the dataUrlWithName and a test case for dataUrlWithoutName.

**Comment by glasserc** [comment]
Thanks!
