### PR TITLE
#804 - Bug Fix - Empty divs are created

### LINKED ISSUE #804: 3 Empty divs are created
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When using rjsf, multiple empty divs seem to be created that are not useful

### Steps to Reproduce

1. Goto https://mozilla-services.github.io/react-jsonschema-form/ 
2. Example "simple" (the default one)
3. If you inspect the first input, you see the following

3 empty divs seem to be created.

#### Expected behavior

No empty divs should be created

#### Actual behavior

3 empty divs are created

### Version

1.0.0

### PR DESCRIPTION
**Pull request by gr8pathik**
### Reasons for making this change

Multiple empty divs seem to be created that are not useful. So removing the empty divs

Resolves #804

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: src/components/fields/ArrayField.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ import {
 function ArrayFieldTitle({ TitleField, idSchema, title, required }) {
   if (!title) {
     // See #312: Ensure compatibility with old versions of React.
```
Comment (epicfaace) [inline src/components/fields/ArrayField.js]: Please remove this line.

File: src/components/fields/ArrayField.js [hunk 2]
```diff
@@ -31,7 +31,7 @@ function ArrayFieldTitle({ TitleField, idSchema, title, required }) {
 function ArrayFieldDescription({ DescriptionField, idSchema, description }) {
   if (!description) {
     // See #312: Ensure compatibility with old versions of React.
```
Comment (epicfaace) [inline src/components/fields/ArrayField.js]: Please remove this line.

**Comment by epicfaace** [comment]
Looks great! Thanks

**Comment by Jigsaw-Jams** [comment]
Has this been released on npm?

**Comment by epicfaace** [comment]
@Jigsaw-Jams it now has.
