### PR TITLE
Fix omitExtraData bugs for nested empties and nonspecified objects

### LINKED ISSUE #1388: Can't enter in data with omitExtraData and liveOmit
### Description

Can't enter in data when `type: object` is not specified.

### Steps to Reproduce

1. Go to [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmb28iOiJhc2QifSwic2NoZW1hIjp7InByb3BlcnRpZXMiOnsiZm9vIjp7InR5cGUiOiJzdHJpbmcifX0sImRlcGVuZGVuY2llcyI6eyJmb28iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiZm9vIjp7ImNvbnN0IjoiYSJ9LCJiYXIiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyJ9LCJtaW5JdGVtcyI6M319fV19fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fX0=).
2. Turn on "omit extra data" and "live omit".
2. Type something in the textbox -- nothing comes up.

### Version

1.7.0

### LINKED ISSUE #1396: Array of objects data entry not working with liveOmit
### Description

Array of objects data entry not working with liveOmit.

### Steps to Reproduce

1. Go to [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6e30sInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyJ9fX19LCJ1aVNjaGVtYSI6e319)
2. Type in a value for "name".

#### Expected behavior

The form data should be

```
[{name: "asdasd"}]
```

#### Actual behavior

The form data is `{}` -- somehow liveOmit is not adding in the data properly.

image

### Version

1.7.0+ (latest version from master)

This seems to be a regression added by PR #1371 .

[PR #1371 demo](https://deploy-preview-1371--trusting-agnesi-d3347d.netlify.com/#eyJmb3JtRGF0YSI6eyJzaG93Ijp0cnVlfSwic2NoZW1hIjp7ImRlZmluaXRpb25zIjp7fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic2hvdyI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwiZGVwZW5kZW5jaWVzIjp7InNob3ciOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsic2hvdyI6eyJjb25zdCI6dHJ1ZX0sInBhcnRpY2lwYW50cyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmcifX19fX19XX19fSwidWlTY2hlbWEiOnt9fQ==)
[
PR #1372 demo (right before #1371)](https://deploy-preview-1372--trusting-agnesi-d3347d.netlify.com/#eyJmb3JtRGF0YSI6eyJzaG93Ijp0cnVlfSwic2NoZW1hIjp7ImRlZmluaXRpb25zIjp7fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic2hvdyI6eyJ0eXBlIjoiYm9vbGVhbiJ9fSwiZGVwZW5kZW5jaWVzIjp7InNob3ciOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsic2hvdyI6eyJjb25zdCI6dHJ1ZX0sInBhcnRpY2lwYW50cyI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJuYW1lIjp7InR5cGUiOiJzdHJpbmcifX19fX19XX19fSwidWlTY2hlbWEiOnt9fQ==)

### PR DESCRIPTION
**Pull request by Tonexus**
### Reasons for making this change

Fixes #1388 and fixes #1396. Alternative to #1418.

Modifies behavior of `toPathSchema` in `utils.js` (afaik the function is only used in omitting the extra data, let me know if this breaks anything else) to create `$name` key for arrays as well to be consistent with behavior for objects. Modifies behavior of `getFieldNames` in `Form.js` to also add a path to the array of paths if that path points to something empty. Refactors the surrounding code to be more concise and, hopefully, readable. Adds tests for `omitExtraData` and `liveOmit`.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -873,43 +873,34 @@ export function toIdSchema(
 
 export function toPathSchema(schema, name = "", definitions, formData = {}) {
   const pathSchema = {
-    $name: name,
+    $name: name.replace(/\.$/, ""),
```
Comment (epicfaace) [inline src/utils.js]: Why is this needed?

File: src/utils.js [hunk 2]
```diff
@@ -873,43 +873,34 @@ export function toIdSchema(
...
+    formData.forEach((element, i) => {
+      pathSchema[i] = toPathSchema(
+        schema.items,
+        `${name}${i}.`,
+        definitions,
+        element
+      );
+    });
+  } else if (schema.hasOwnProperty("properties")) {
+    for (const property in schema.properties || {}) {
```
Comment (epicfaace) [inline src/utils.js]: Can we just make this:

```suggestion
    for (const property in schema.properties) {
```

File: src/utils.js [hunk 3]
```diff
@@ -873,43 +873,34 @@ export function toIdSchema(
 
 export function toPathSchema(schema, name = "", definitions, formData = {}) {
```
Comment (epicfaace) [inline src/utils.js]: Are you changing the functionality of toPathSchema in some way or just refactoring it?

**Comment by epicfaace** [comment]
> Modifies behavior of `getFieldNames` in `Form.js` to also add a path to the array of paths if that path points to something empty.

My PR #1418 also does this, although the way it does so isn't very good -- it relies on looking for the first "." in the string (which could be an issue with specially-named keys later). Your method seems better!

https://github.com/mozilla-services/react-jsonschema-form/pull/1418/files#diff-07a63ede6fe55fca89398d42da737369R170

File: src/utils.js (hunk 1 above)
Comment (Tonexus) [reply src/utils.js]: As a result of refactoring and because the initial call starts with name as an empty string, I ended up with a period prepended to all of the `$name`s, so I swapped it such that the period is appended, then removed when the `$name` value is set. e.g. here

https://github.com/Tonexus/react-jsonschema-form/blob/ff66b13dd0e74a36394f3e45e546137b024d709e/src/utils.js#L890

changes `` `${name}.${i}` `` to `` `${name}${i}.` ``.

Now that I think about it, it was honestly was kind of an arbitrary change. If you think the old style is more clear, I can change it back.

File: src/utils.js (hunk 3 above)
Comment (Tonexus) [reply src/utils.js]: I am changing the functionality of `toPathSchema`. Previously, if you had

```
schema = {
    type: "object",
    properties: {
        values: {
            type: "array",
            items: {
                type: "string"
            }
        }
    }
}

formData = {
    values: ["asdf", "ghkj"]
}
```

`toPathSchema(schema, formData = formData)` would not give the array a `$name` key, and would be

```
pathSchema = {
    $name: "",
    values: {
        0: {
            $name: "values.0"
        },
        1: {
            $name: "values.1"
        }
    }
}
```

My change results in

```
pathSchema = {
    $name: "",
    values: {
        $name: "values",
        0: {
            $name: "values.0"
        },
        1: {
            $name: "values.1"
        }
    }
}
```

which I believe is more consistent since there's a `$name` for ALL nesting. Again, I made this functionality change because it looks like `toPathSchema` is only used for omitting extra data and does not break anything else. This makes it easier to traverse the path schema and get the path if the array is empty.

File: src/utils.js (hunk 2 above)
Comment (Tonexus) [reply src/utils.js]: I think that should be fine. I'll check it out.

File: src/utils.js (hunk 1 above)
Comment (epicfaace) [reply src/utils.js]: I think you can change it to the old style, unless there are any additional advantages to this new style.

**Comment by Tonexus** [comment]
@epicfaace I added your tests, and if I understand correctly, `describeRepeated` essentially parameterizes the tests and runs the 3 relevant combinations of `omitExtraData` and `liveOmit` for the enclosed tests. In using the function in `Form_test.js`, you repeat all of the current tests for the 3 combinations, right? So then there are no tests to make sure that `omitExtraData` actually omits the correct data yet, right?

**Comment by epicfaace** [comment]
> @epicfaace I added your tests, and if I understand correctly, `describeRepeated` essentially parameterizes the tests and runs the 3 relevant combinations of `omitExtraData` and `liveOmit` for the enclosed tests. In using the function in `Form_test.js`, you repeat all of the current tests for the 3 combinations, right?

Yes.

> So then there are no tests to make sure that `omitExtraData` actually omits the correct data yet, right?

There are tests at the end of Form_test.js that are not within the `describeRepeated` block; I believe they include a test that tests that behavior of `omitExtraData`.

**Comment by epicfaace** [comment]
By the way, the test that is failing is due to issues with form defaults when omitExtraData and/or liveOmit are true. I fixed them in the other PR with these changes: https://github.com/mozilla-services/react-jsonschema-form/pull/1418/files#diff-07a63ede6fe55fca89398d42da737369R249-R253

**Comment by Tonexus** [comment]
Yeah I see what you are doing, but I think that that logic can be moved to `onChange` instead. Right now, you have to recompute `pathSchema` on submit to fix the bug, but it should really be computed whenever the form data changes, as the paths don't actually change on submit.

**Comment by epicfaace** [comment]
@Tonexus ok, but if `omitExtraData` is true and `liveOmit` is false, then don't we only need to compute the `pathSchema` on submit? Computing it during `onChange` is unnecessary and might slow things down.

**Comment by Tonexus** [comment]
@epicfaace That's a good point, if `liveOmit` is false, `pathSchema` probably doesn't need to be computed. However, it looks like `pathSchema` is already being computed on component creation and on props change without checking for `liveOmit`, and I wanted to be consistent with those cases. Should I change those cases to check for `omitExtraData` and `liveOmit` as well?

Also, right now it looks like `pathSchema` is not propagated to the state in `onChange` even if both `omitExtraData` and `liveOmit` are true, so I'll go ahead and change it so that `pathSchema` is propagated there as well.

**Comment by epicfaace** [comment]
> @epicfaace That's a good point, if `liveOmit` is false, `pathSchema` probably doesn't need to be computed. However, it looks like `pathSchema` is already being computed on component creation and on props change without checking for `liveOmit`, and I wanted to be consistent with those cases. Should I change those cases to check for `omitExtraData` and `liveOmit` as well?

Yes, please do.

> Also, right now it looks like `pathSchema` is not propagated to the state in `onChange` even if both `omitExtraData` and `liveOmit` are true, so I'll go ahead and change it so that `pathSchema` is propagated there as well.

Sounds good, thanks!

**Comment by Tonexus** [comment]
@epicfaace Actually, should `pathSchema` even be part of the state? It is only computed on submit or, with `liveOmit` true, whenever `formData` changes. And then it is only applied directly after those two cases, so it doesn't really need to persist.

On a side note, a lot of the logic in `onChange` and `onSubmit` seem redundant, maybe some of it can be refactored in another PR...

**Comment by Tonexus** [comment]
@epicfaace I'm now having issues with the very last test case in the file.

https://github.com/Tonexus/react-jsonschema-form/blob/d23c6480175cf5eb1c041bdb1b7df67eabd0a515/test/Form_test.js#L2663-L2687

Can you explain the reasoning for that one? It looks like it is correctly applying the new `schema` to the new `formData`. Is it supposed to use the new `formData` with the old `schema` that then removes the `baz` property?

**Comment by epicfaace** [comment]
> @epicfaace Actually, should `pathSchema` even be part of the state?

Yeah, you're right.

For the very last test case, you're right, I think the test case is wrong. I based it off an original test that tested based on an _external_ (props-based) formData change, which used `comp.componentWillReceiveProps`. I meant to change the test to be based on an _internal_ (user interaction-based) formData change, using `Simulate.change`. However, this test (as well as the one before it) mixes up both types of props changes in the same test case. Essentially, I meant to remove the `comp.componentWillReceiveProps` call, but neglected to.

It may be good to split this up; for each test in the final "Schema and formData updates" `describe` block, make one test that uses `comp.componentWillReceiveProps` to test an external formData change and another test that tests `Simulate.change` to test the internal formData change.

**Comment by Tonexus** [comment]
@epicfaace Ok, made those changes. There are now 4 new tests for each combo of `omitExtraData` and `liveOmit`, and only one actually omits data on form change. Should be ready for review/merge now.

File: src/utils.js (hunk 3 above)
Comment (epicfaace) [reply src/utils.js]: Got it, thanks!

**Comment by epicfaace** [comment]
Oh, I remember why pathSchema was initially part of the state. The idea was that it could be passed on to widgets/fields eventually, so that they would be able to know the "path" of the formData that they refer to. However, given that pathSchema is only computed live when `liveOmit` is true, there would be no point keeping it in the state for now. We can re-add pathSchema into the state later on (later PR) when also giving access to it for widgets/fields.

File: src/components/Form.js [hunk 4]
```diff
@@ -148,23 +147,16 @@ export default class Form extends Component {
...
-          }
-        } else if (key === "$name") {
+          let newPaths = paths.map(path => `${path}.${key}`);
+          getAllPaths(_obj[key], acc, newPaths);
+        } else if (key === "$name" && _obj[key] !== "") {
           paths.forEach(path => {
+            path = path.replace(/^\./, "");
             const formValue = _get(formData, path);
-            if (typeof formValue !== "object") {
+            if (typeof formValue !== "object" || _isEmpty(formValue)) {
```
[the remark this answers is not in the document]
Comment (Tonexus) [reply src/components/Form.js]: The empty array behavior is intentional. It fixes the behavior where if there is an empty array inside of an array, `_pick` will remove both arrays if the path to the inner (empty) array is not provided. Also, it looks like the default behavior if `liveOmit` is off is that deleting all array items does not remove the key/value pair containing the array, so `liveOmit` being true should behave the same, as the property is still defined in the schema. Maybe there needs to be a fix for the default behavior of removing the last element in an array in general.

In regards to the conditional, I added a comment, and I think that makes it clear enough. The code already uses the fact `typeof [] === "object"` in some other places as well, so I think that we should just assume that that fact is common knowledge.

**Comment by Tonexus** [comment]
@epicfaace Added most of the requested changes. See review comment.

File: src/components/Form.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (epicfaace) [reply src/components/Form.js]: Makes sense, thanks for the explanation!

**Comment by MatinF** [comment]
Happy to do some tests of this to see if it resolves #1396 and #1425 - is the playground link updated?

**Comment by epicfaace** [comment]
You can use the playground link for the deploy preview of this PR: https://deploy-preview-1419--rjsf.netlify.com/
