### PR TITLE
Fix nested dependencies updating

### LINKED ISSUE #1235: Nested dependencies not updated correctly
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When there are nested dependencies, updating top most dependency does not properly update form data for the nested ones, resulting incorrect form rendering.

### Steps to Reproduce

1. Open this [form](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJlbXBsb3llZV9hY2NvdW50cyI6ZmFsc2UsImZpcnN0TmFtZSI6IkNodWNrIiwibGFzdE5hbWUiOiJOb3JyaXMiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwiaWQiOiJzb21laWQiLCJkZXBlbmRlbmNpZXMiOnsiZW1wbG95ZWVfYWNjb3VudHMiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiZW1wbG95ZWVfYWNjb3VudHMiOnsiY29uc3QiOnRydWV9LCJ1cGRhdGVfYWJzZW5jZXMiOnsidGl0bGUiOiJVcGRhdGUgQWJzZW5jZXMiLCJ0eXBlIjoic3RyaW5nIiwib25lT2YiOlt7InRpdGxlIjoiQm90aCIsImNvbnN0IjoiQk9USCJ9LHsidGl0bGUiOiJNZWRpY2FsIG9ubHkiLCJjb25zdCI6Ik1FRElDQUxfT05MWSJ9LHsidGl0bGUiOiJOb24tTWVkaWNhbCBPbmx5IiwiY29uc3QiOiJOT05fTUVESUNBTF9PTkxZIn0seyJ0aXRsZSI6Ik5vbmUiLCJjb25zdCI6Ik5PTkUifV19fX1dfSwidXBkYXRlX2Fic2VuY2VzIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7InBlcm1pdHRlZF9leHRlbnNpb24iOnsidGl0bGUiOiJQZXJtaXR0ZWQgRXh0ZW5zaW9uIiwidHlwZSI6ImludGVnZXIifSwidXBkYXRlX2Fic2VuY2VzIjp7ImNvbnN0IjoiQk9USCJ9fX0seyJwcm9wZXJ0aWVzIjp7InBlcm1pdHRlZF9leHRlbnNpb24iOnsidGl0bGUiOiJQZXJtaXR0ZWQgRXh0ZW5zaW9uIiwidHlwZSI6ImludGVnZXIifSwidXBkYXRlX2Fic2VuY2VzIjp7ImNvbnN0IjoiTUVESUNBTF9PTkxZIn19fSx7InByb3BlcnRpZXMiOnsicGVybWl0dGVkX2V4dGVuc2lvbiI6eyJ0aXRsZSI6IlBlcm1pdHRlZCBFeHRlbnNpb24iLCJ0eXBlIjoiaW50ZWdlciJ9LCJ1cGRhdGVfYWJzZW5jZXMiOnsiY29uc3QiOiJOT05fTUVESUNBTF9PTkxZIn19fV19fSwicHJvcGVydGllcyI6eyJlbXBsb3llZV9hY2NvdW50cyI6eyJ0eXBlIjoiYm9vbGVhbiIsInRpdGxlIjoiRW1wbG95ZWUgQWNjb3VudHMifX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX19)
2. Check employee accounts
3. From update absences select BOTH
4. Permitted Extension appears correctly
5. Now uncheck employee accounts
6. Permitted Extension still shows, but it should not because it is dependency of update absences, which should only shows when employee accounts is true.

#### Expected behavior

Permitted Extension should be hidden and all form data related to those nested dependencies removed.

#### Actual behavior

Permitted Extension still shows and the value of update absences is in the form data

### Version

1.3.0

### PR DESCRIPTION
**Pull request by epicfaace**
### Reasons for making this change

Fixes #1235.

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -595,6 +618,12 @@ function resolveDependencies(schema, definitions, formData) {
         dependencyValue
       );
     }
+    return processDependencies(
```
Comment (epicfaace) [inline src/utils.js]: Makes this function recursive so that once a dependency is resolved, it goes through all the dependencies again.

Comment (epicfaace) [inline src/utils.js]: Makes this function recursive so that once a dependency is resolved, it goes through all the dependencies again.
