### PR TITLE
Experiment: external form validation.

### LINKED ISSUE #146: Allow passing an errorSchema to the form component instance?
Refs #144.

If some validation can only be performed server side, do we want to offer the capability of informing the client-side form component that something has failed externally? That would mean exposing an `errorSchema` prop and being able to augment the current errorSchema with supplementary information retrieved from *elsewhere*.

The main problem being that we'll have to keep the state of these information during the lifecycle of the component, which is likely to be hard to achieve (meaning merging external with internal state, notably).

Another approach would be to only rely on custom validation at the field level as suggested in #145, but then we should ensure async validation (eg. with server side communication involved) is allowed.

Thoughts on this?

### PR DESCRIPTION
**Pull request by n1k0**
Refs #144, #145.

This introduces a new `validate` Form prop which accepts a function receiving `formData` and an error handler object exposing an API to add errors to the targeted field nodes in the tree. 

Here's the pitch:

```js
function validate({pass1, pass2}, errors) {
  if (pass1 !== pass2) {
    errors.pass2.addError("Passwords don't match");
  }
  return errors;
}

const schema = {
  type: "object",
  properties: {
    pass1: {type: "string", minLength: 3},
    pass2: {type: "string", minLength: 3},
  }
};

render(<Form schema={schema} validate={validate} />);
```

Note that this doesn't solve #155, which should be addressed in a separate issue. This is most likely to close #146 though.

### TODO

- [x] Support for custom validator
- [ ] Async support
- [ ] Documentation

### CODE REVIEW

**Comment by n1k0** [comment]
Ideally I'd like to offer a really convenient API for denoting fields in error. Something like this:

```js
function validate({pass1, pass2}) {
  if (pass1.value !== pass2.value) {
    pass2.error("Passwords don't match");
  }
}
```

**Comment by Chachaproper** [comment]
Perfect. I tested in the context of my project. 
The second option seems preferable.

**Comment by n1k0** [comment]
> Perfect. I tested in the context of my project.

Thanks a lot for your feedback.

> The second option seems preferable.

Yeah, I agree. I'll work on this asap.

**Comment by MoOx** [comment]
I am very new to this package, but sounds like a good start, and far better than nothing :)

**Comment by n1k0** [comment]
I've progressed in my attempt at improving the validation API in 5a6984e34ebbf1280b26e4aad1b6a58ad40466bd, but the code is rather convoluted for what it's trying to achieve.

I'll spend more time to try to simplify things as much as I can here.

**Comment by n1k0** [comment]
Now this needs to handle async validation through promises, which is our next implementation step.

**Comment by n1k0** [comment]
Defenitely not very happy with that custom validation API, no mention of its current implementation... Would love some feedback from you guys if you have any other approach in mind. /cc @glasserc

**Comment by n1k0** [comment]
Trying to directly use the return value from the custom validate function in https://github.com/mozilla-services/react-jsonschema-form/pull/163/commits/8d047dec379e39b2b4530a05eedaf8676a8f2149, doesn't feel much better :(

```js
function validate(formData) {
  const {pass1, pass2} = formData;
  if (pass1.getValue() !== pass2.getValue()) {
    pass2.addError("Passwords don't match");
  }
  return formData;
}
```

**Comment by n1k0** [comment]
Now I think about it, I wonder if this wouldn't be much better:

```js
function validate({pass1, pass2}, {getValue, addError}) {
  if (getValue(pass1) !== getValue(pass2)) {
    addError(pass2, "Passwords don't match");
  }
}
```

I'm not 100% sure it's doable but it most definitely looks better. Will keep investigating.

**Comment by glasserc** [comment]
Maybe you already considered this and discarded it, but how about something like one of these?

```javascript
function validate({pass1, pass2}) {
    let errors = {};
    if (pass1 !== pass2) {
        errors.pass2 = "passwords don't match";  // and also accept arrays like ["passwords don't match"]
    }
    return errors;
}
```

or

```javascript
function validate({pass1, pass2}) {
    const errors = new FormValidateResult();
    if (pass1 !== pass2) {
        errors.addError("pass2", "passwords don't match");
    }
    return errors;    // no return value means no errors
}
```

(You could also pass the FormValidateResult as another argument to the function, in which case the user might not have to return it.)

File: src/components/Form.js [hunk 1]
```diff
@@ -51,8 +53,13 @@ export default class Form extends Component {
...
 
   validate(formData, schema) {
-    const validator = new Validator();
-    return validator.validate(formData, schema || this.props.schema).errors;
+    const {validate} = this.props;
+    const {errors} = jsonValidate(formData, schema || this.props.schema);
+    const errorSchema = toErrorSchema(errors);
+    if (typeof validate === "function") {
+      return userValidate(validate, formData, errorSchema);
+    }
```
Comment (glasserc) [inline src/components/Form.js]: I might be missing something obvious here, but it seems like if you go down this code path, you lose `errors`. Is that OK? Is it only necessary to keep `errorSchema`?

**Comment by n1k0** [comment]
> errors.addError("pass2", "passwords don't match");

The thing is you need to know which node matches this `pass2` identifier, which might get tricky with deeply nested structures.

File: src/components/Form.js (hunk 1 above)
Comment (n1k0) [inline src/components/Form.js]: userValidate will return an `errors` property, recomputed against the internally augmented `errorSchema`. 

I know :(

**Comment by glasserc** [comment]
Oops, I didn't consider nested structures. I guess you could take dotted paths like `"obj.user.auth.pass2"` or arrays like `["obj", "user", "auth", "pass2"]`. 

How about:

```javascript
function validate({user: {auth: {pass1, pass2}}}, errors) {
    if (pass1 !== pass2) {
        errors.user.auth.pass2.addError("passwords don't match");
    }
}
```

or

```javascript
function validate(formData) {
    const errors = new FormValidatorResult(formData);
    const {pass1, pass2} = formData.user.auth;
    if (pass1 !== pass2) {
        errors.user.auth.pass2.addError("passwords don't match");
    }
    return errors;
}
```

I don't like the need to use `getValue` to access the value of the fields. I think this is part of what you were saying feels too "object oriented". I'm OK with mutating a given object and expecting the caller to notice that it got mutated; this frees you from accidentally not returning something. I'm also OK with making the validate function not mutate anything and just "purely" return some kind of object that describes the errors we found. In this case I think we should provide some kind of helper to make it easier to accumulate errors, and maybe we should enforce that the user always returns *something* so that we can help them catch the situation where they forgot to put a return statement.

**Comment by n1k0** [comment]
I like the idea of passing two distinct object; the first one would be the initial, untouched `formData` object and the second one being an object exposing an API to append errors appropriately, its structure being predefined. Thank you, that's very helpful :)

**Comment by n1k0** [comment]
@glasserc implemented your first suggestion in https://github.com/mozilla-services/react-jsonschema-form/pull/163/commits/e1d42a5cb3efd854e311b02c45b2056ef778bae7, would love to hear your feedback :)

There's room for improvement and many more tests to write, but I feel we're at least on the right track. Thoughts?

**Comment by glasserc** [comment]
I agree! 

- I don't think we should expect the user to return something. What could they possibly return besides the thing we gave them, which they've already mutated? If they do return something, we'll try to unwrap it, which probably won't work it.
- Can we initialize the error "handler" from the data in the `errorSchema`, so that we don't have to do a merge later?

This question might be outside the scope of this PR, but why do we store both `errors` and `errorSchema`? It seems like the only place we use it is in the toplevel `Form`. Can we just keep the `errorSchema` around an generate `errors` once when we need it there?

File: src/validate.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
+import { isObject, toErrorList, mergeObjects } from "./utils";
+
+
+function createErrorHandler(formData) {
+  const handler = {
+    __errors: [],
+    addError(message) {
+      this.__errors = [...this.__errors, message];
```
Comment (glasserc) [inline src/validate.js]: Why not just use `push`?

File: src/validate.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+  }
+  return handler;
+}
+
+function unwrapErrorHandler(errorHandler) {
+  return Object.keys(errorHandler).reduce((acc, key) => {
+    if (key === "addError") {
+      return acc;
+    } else if (key === "__errors") {
+      return {...acc, [key]: errorHandler[key]};
```
Comment (glasserc) [inline src/validate.js]: I don't think this is right...

Comment (n1k0) [inline src/validate.js]: Why? If the key is named `__errors` we want the accumulator to have it as well. Maybe that's just poor naming that confused you here? Or am I missing something else?

File: src/validate.js (hunk 2 above)
Comment (n1k0) [inline src/validate.js]: Because why not not? :D I must confess I like this syntax more, but push works too. I'm not too attached to it though, so... your call.

**Comment by n1k0** [comment]
> - I don't think we should expect the user to return something. What could they possibly return besides the thing we gave them, which they've already mutated? If they do return something, we'll try to unwrap it, which probably won't work it.

The thing is, we'll have at some point to accept their function to return a `Promise` so we can support asynchronous validation.

> - Can we initialize the error "handler" from the data in the `errorSchema`, so that we don't have to do a merge later?

We could probably do that indeed.

> This question might be outside the scope of this PR, but why do we store both `errors` and `errorSchema`? 

The `errors` list is what our jsonschema lib gives us when validating data against a JSON schema. It's useful to list error in a flat fashion, like what we do for the error list at the top of the form.

The `errorSchema` map is the representation of that list as a tree, which is more convenient to propagate down our component tree so they can reflect errors contextually to their node in that tree.

> It seems like the only place we use it is in the toplevel `Form`. Can we just keep the `errorSchema` around an generate `errors` once when we need it there?

So as 

1. the `errors` list is what we get from the jsonschema validatio lib, and
2. it's used to render the flat list of errors at the top of the form

I'm afreaid we'll need to keep it around.

If you have a good plan for factorizing all this mess efficiently, I'm all ears :)

Thanks again for taking the time to provide feedback on this tricky topic!

**Comment by glasserc** [comment]
Oh, yeah, promises, I didn't even consider that. Thanks.

File: src/validate.js (hunk 3 above)
Comment (glasserc) [inline src/validate.js]: I had assumed the output of unwrapping ``{a: {b: {__errors: ["an error on a.b"]}}}`` should be ``{a: {b: ["an error on a.b"]}}``. But thinking about it now, maybe you're trying to permit someone to add an error to an "internal" node like a user as well as "leaf" nodes like password fields.

File: src/validate.js (hunk 2 above)
Comment (glasserc) [inline src/validate.js]: This, and the definition of `reduce` to return new objects every iteration, feel a little scary to me because they won't be as efficient as mutating objects in-place, and I'm not sure the JS RTS is smart enough to optimize the update into an in-place mutation. I know this is JS and we probably don't care about the overhead of copying objects, but it just feels wasteful to me and not very idiomatic. But JS isn't my best language so I'm willing to accept whatever here.

File: src/validate.js (hunk 3 above)
Comment (n1k0) [inline src/validate.js]: > maybe you're trying to permit someone to add an error to an "internal" node

Yes.

File: src/validate.js (hunk 2 above)
Comment (n1k0) [inline src/validate.js]: I won't go the microbenchmark route, but I have a hunch the impact on perfs would be rather small here. Anyway I can switch back to `push` anyway if that makes you more comfortable with the change.

File: test/utils_test.js [hunk 4]
```diff
@@ -603,4 +627,23 @@ describe("utils", () => {
...
+          b: {
+            __errors: ["err1", "err2"]
+          }
+        },
+        c: {
+          __errors: ["err3"]
+        }
+      })).eql([
+        {stack: "b err1"},
+        {stack: "b err2"},
```
Comment (glasserc) [inline test/utils_test.js]: Shouldn't these be `a.b` ?

Comment (n1k0) [inline test/utils_test.js]: In theory yes, but that would mean generating these paths. I may work on this, but I'm wondering about the added value. There's some for sure, but I'm pretty sure things would stay useable without full field path info. Need to think about it.

Comment (glasserc) [inline test/utils_test.js]: Well, this output format no longer corresponds to the `jsonschema` return type. Specifically, in `jsonschema` it would be `instance.a.b`, and there would be properties called `property`, `name`, `instance`, etc. I think we should either match that output or document the format we're producing instead. I don't have a very clear sense of what the use case is for the error list, so I don't know which is better. It looks like you intend for `stack` to be usable directly as an error message, so maybe we should call it `errorMsg`. I think we will probably find that having the path available is going to be useful eventually even if it doesn't show up in the error message (that's why `jsonschema` provides it).

Comment (n1k0) [inline test/utils_test.js]: > Well, this output format no longer corresponds to the `jsonschema` return type.

I don't want to stick to the format exposed by *jsonschema* too much, mostly because I'm not finding it super convenient as it uses custom error class instances, and because I'd like to decouple our implementation from their API as much as I can. For example, *jsonschema* doesn't allow defining our very own error messages instead of their builtins (eg. see #155), and we may want to investigate other libraries at some point.

> Specifically, in `jsonschema` it would be `instance.a.b`, and there would be properties called `property`, `name`, `instance`, etc. 

... and `stack`, indeed, which is the *jsonschema* property name they use for storing the complete error message. Hence why I'm complying here.

> I think we should either match that output or document the format we're producing instead. 

We must define our API and associated format before documenting it; be sure I'll update docs as soon as the ongoing implementation is validated :)

> I don't have a very clear sense of what the use case is for the error list, so I don't know which is better. 

The use case is for displaying the list of all errors at the top of the form, in a flat fashion:



This capture is made against [the hosted demo](http://mozilla-services.github.io/react-jsonschema-form/) (see the *Errors* tab).

As you can see, iterating over the error list is pretty much straigthforward to render this. Basically we really do have the two distinct use cases of

1. rendering a flat list of errors at the top of the form (our `errors` list);
2. rendering errors contextually to their field level, which needs a tree (our `errorSchema` map).

> It looks like you intend for `stack` to be usable directly as an error message, so maybe we should call it `errorMsg`.

No because as mentioned previously, I need to comply with the *jsonschema* format which uses a `stack` property to store the full error description string.

> I think we will probably find that having the path available is going to be useful eventually even if it doesn't show up in the error message (that's why `jsonschema` provides it).

Yeah that's why I still need to think about it. My main concern is we're already processing a lot of this stuff from one format to another and vice versa. We could invent some intermediary format, which is likely to look a lot like the `{errors, errorSchema}` one we already have (as, again, we actually need both data structures). Just need to ensure we're not wasting too many CPU cycles going back and forth here.

**Comment by leplatrem** [comment]
Ethan, we decided to move forward and land this. We spawned some issues, if there is anything that you'd like to see addressed, please open an issue or chase us ;)
