### PR TITLE
Limit cases where "required" attribute is used on checkboxes

### LINKED ISSUE #338: Boolean checkbox can't send false
### Prerequisites
- [ x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

Boolean checkbox's require you to tick the box, you cannot send a false.  
### Steps to Reproduce

Create a  form where a boolean field is required
#### Expected behavior

Either a unticked / ticked state will be accepted
#### Actual behavior

Only a ticked box is accepted.  

I'm using a jsonschema-form to send a  json to an api that uses https://github.com/geraintluff/tv4 as a validator using the same schema.  tv4's interpretation of a required boolean is it can be true or false as long as it is present.  Which implementation is right?
### Version

^0.38.0

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #338

If the "required" attribute is applied to a checkbox, then HTML5
validation will only pass if the checkbox is ticked. This is at odds
with the JSON schema definition of "required" that simply requires that
the key exists.

This PR will make it so that the "required" HTML5 attribute will only be
applied if the schema uses `{ const: true }` or `{ enum: [ true ] }`.

Signed-off-by: Lucian <lucian.buzzo@gmail.com>

### Reasons for making this change

[Please describe them here]

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
@LucianBuzzo What about this schema?

```
{
      "type": "boolean",
      "oneOf": [
        {
          "const": true
        }
      ]
}
```

File: src/components/widgets/CheckboxWidget.js [hunk 1]
```diff
@@ -16,6 +15,14 @@ function CheckboxWidget(props) {
     onFocus,
     onChange,
   } = props;
+
+  // Because an unchecked checkbox will cause html5 validation to fail, only add
+  // the "required" attribute if the field value must be "true", due to the
+  // "const" or "enum" keywords
+  const required =
+    schema.const ||
```
Comment (epicfaace) [inline src/components/widgets/CheckboxWidget.js]: Do you think we need to put this, or is it unnecessary?:
```suggestion
    schema.const === true ||
```

Comment (LucianBuzzo) [reply src/components/widgets/CheckboxWidget.js]: It feels a bit unnecessary, we only really want to check that `const` is truthy

**Comment by epicfaace** [comment]
> @LucianBuzzo What about this schema?
> 
> ```
> {
>       "type": "boolean",
>       "oneOf": [
>         {
>           "const": true
>         }
>       ]
> }
> ```

@LucianBuzzo Just bumping this.

**Comment by LucianBuzzo** [comment]
@epicfaace Thanks for the reminder, I'll hopefully get time to add this case this afternoon

**Comment by LucianBuzzo** [comment]
@epicfaace I've added additional logic for handling cases where `anyOf`, `oneOf` and `allOf` would require the field to be `true`

**Comment by epicfaace** [comment]
Looks great!
