### PR TITLE
Correctly use $ref when matching options with oneOf

### LINKED ISSUE #1173: Issue with nesting oneOf inside an array that is inside of an object.
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I am attempting to use oneOf to create an array, which will be filled with objects. These objects will have a string along with an array. 
this is the expected formData or object I want to receive on the backend:
```
{
typeProp: 'verify',
verifications: [
  {
    service: 'myService',
    endpoints: [
      {
        Description: 'myService1',
        Id: ''
      },
      {
        Description: 'myService2',
        Id: ''
      },
      {
        Description: 'myService3',
        Id: ''
      }
    ]
  },
  {
    serviceName: 'yourService',
    endpoints: [
      {
        endpointDescription: 'yourService1',
        endpointId: ''
      },
      {
        endpointDescription: 'yourService2',
        endpointId: ''
      }
    ]
  }
]
}
```

I am trying to use a dropdown on my typeProp, which would then show a dropdown for the service, once a selection is made for the service, I need the endpoints to show and also be a dropdown. Basically, all 3 fields will need to be a oneOf dropdown. 

Now, oneOf seems to be the best solution for me. However, the oneOf functionality does not seem to be able to be nested. Is there a way around this? Does anyone have a solution to my problem, or is this a bug in the code that will need to be reviewed? Any help is greatly appreciated

I'm not sure how to add a playground, but here is the code I currently have. I have tried every thing imagine-able of where to put the next oneOf but cannot find a solution.

Here is my code: 
```
{
      title: 'New,
      description: 'Create',
      type: 'object',
      properties: {
        type: {
          type: 'string',
          title: 'Type',
          enum: [
            'verification',
            'subscription'
          ]
        }
      },
      dependencies: {
        type: {
          oneOf: [
            {
              properties: {
                type: {
                  enum: ['verification']
                },
                verification: {
                  type: 'array',
                  title: 'Verifications',
                  items: {
                    type: 'object',
                    properties: {
                      serviceName: {
                        type: 'string',
                        title: 'Service Name',
                        enum: ['myService']
                      },
                      endpoints: {
                        type: 'array',
                        title: 'End Points',
                        items: {
                          type: 'object',
                          properties: {
                            endpointDesc: {
                              type: 'string',
                              title: 'EP Name',
                              enum: ['MyServiceEP']
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
```

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #1173

Additionally, if a matching option isn't found, preserve the currently
selected option

Change-type: patch
Signed-off-by: Lucian <lucian.buzzo@gmail.com>

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by bdgeise** [comment]
@LucianBuzzo - Thanks for taking a look at this so quickly.  I have another example that I believe is the same or at least similar and doesn't work as expected on the branch for this issue.  If you want a new issue for this please let me know.

https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzdGVwcyI6W3siYWN0aW9ucyI6W3sidmFsdWUiOnsicnVsZXMiOlt7Im9wZXJhdG9yIjoiYW5kIn1dfX1dfV0sImZpcnN0TmFtZSI6IkNodWNrIiwibGFzdE5hbWUiOiJOb3JyaXMiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIn0sInNjaGVtYSI6eyJkZWZpbml0aW9ucyI6eyJmaWx0ZXJUeXBlIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im9wZXJhdG9yIjp7InR5cGUiOiJzdHJpbmcifSwicnVsZXMiOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsib25lT2YiOlt7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImZpZWxkIjp7InRpdGxlIjoiRmlsdGVyIGZpZWxkIiwidHlwZSI6InN0cmluZyJ9LCJvcGVyYXRvciI6eyJ0aXRsZSI6IkZpbHRlciBjb25kaXRpb24gb3BlcmF0b3IiLCJ0eXBlIjoic3RyaW5nIn0sInZhbHVlIjp7InRpdGxlIjoiVmFsdWVzIHRvIGZpbHRlciBvbiIsInR5cGUiOiJhcnJheSIsIml0ZW1zIjp7Im9uZU9mIjpbeyJ0aXRsZSI6IlN0cmluZyBUeXBlIiwidHlwZSI6InN0cmluZyJ9LHsidGl0bGUiOiJOdW1lcmljIFR5cGUiLCJ0eXBlIjoibnVtYmVyIn1dfX19fSx7InR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9maWx0ZXJUeXBlIn1dfX19fSwiZmllbGQiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsdWUiOnsidHlwZSI6InN0cmluZyJ9LCJhbGlhcyI6eyJ0eXBlIjoic3RyaW5nIn19fSwiZmllbGRFaXRoZXIiOnsidHlwZSI6Im9iamVjdCIsIm9uZU9mIjpbeyJ0aXRsZSI6IlNpbXBsZSBmaWVsZCIsIiRyZWYiOiIjL2RlZmluaXRpb25zL2ZpZWxkIn0seyJ0aXRsZSI6IkNvbXBsZXggZmllbGQiLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ2YWx1ZSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9maWVsZEVpdGhlciJ9fSwiYWxpYXMiOnsidHlwZSI6InN0cmluZyJ9fX1dfX0sInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hbWUiOnsidHlwZSI6InN0cmluZyJ9LCJ2ZW5kb3IiOnsidHlwZSI6InN0cmluZyJ9LCJzdGVwcyI6eyJ0eXBlIjoiYXJyYXkiLCJtaW5JdGVtcyI6MSwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsic3RlcF9uYW1lIjp7InR5cGUiOiJzdHJpbmcifSwiYWN0aW9ucyI6eyJ0eXBlIjoiYXJyYXkiLCJtaW5JdGVtcyI6MSwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidHlwZSI6eyJ0aXRsZSI6IkFjdGlvbiBUeXBlIiwiZGVzY3JpcHRpb24iOiJUeXBlIG9mIGFjdGlvbiB0byBiZSBwZXJmb3JtZWQiLCJ0eXBlIjoic3RyaW5nIn0sIm5hbWUiOnsidGl0bGUiOiJBY3Rpb24gTmFtZSIsImRlc2NyaXB0aW9uIjoiSHVtYW4gZnJpZW5kbHkgYWN0aW9uIG5hbWUiLCJ0eXBlIjoic3RyaW5nIn0sInZhbHVlIjp7InRpdGxlIjoiQWN0aW9uIGRlZmluaXRpb24iLCJkZXNjcmlwdGlvbiI6IkRlZmluaXRpb24gZGVmaW5pbmcgdGhlIGFjdGlvbiIsIm9uZU9mIjpbeyJ0aXRsZSI6IkZpbHRlciIsInR5cGUiOiJvYmplY3QiLCIkcmVmIjoiIy9kZWZpbml0aW9ucy9maWx0ZXJUeXBlIn1dfX19fX19fX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX19

File: src/components/fields/MultiSchemaField.js [hunk 1]
```diff
@@ -81,15 +94,20 @@ class AnyOfField extends Component {
       }
     }
 
-    // If the form data matches none of the options, use the first option
-    return 0;
+    // If the form data matches none of the options, use the currently selected
+    // option, assuming its available, otherwise use the first option
```
Comment (epicfaace) [inline src/components/fields/MultiSchemaField.js]:
```suggestion
    // option, assuming it's available; otherwise use the first option
```

**Comment by LucianBuzzo** [comment]
@bdgeise Would you be able to open a new issue for this please?

**Comment by bdgeise** [comment]
> @bdgeise Would you be able to open a new issue for the unexpected behaviour please?
> There is a lot of complicated logic going on here, and I'd like to separate out bugs into different issues/prs as much as possible.

Yep - #1288
